### ISSUE TITLE
`reset_to_home.py` causes error on pr1040 but not on gazebo simulator

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/mohou_ros#64]
`rosrun mohou_ros reset_to_home.py` on real robot
causes the following error 
```
[ERROR] [1662316480.793608]: 1 non-controlling joint angles are not consistent with home position.
{'joint_name': 'head_tilt_joint', 'angle': 1.1361046232931888, 'angle_desired': 1.0728538912009142, 'error': 0.06325073209227461, 'threshold': 0.03490658503988659}
```

However, in the gazebo simulator,  
```
roslaunch pr2_gazebo pr2_empty_world.launch
```
the same command works without problem.

### home position
home_position.yaml 
```yaml
bl_caster_l_wheel_joint: -1747.4960929448357
bl_caster_r_wheel_joint: -1598.6965015232092
bl_caster_rotation_joint: 0.7839066620752853
br_caster_l_wheel_joint: 1070.9315347971171
br_caster_r_wheel_joint: 1234.7029486263784
br_caster_rotation_joint: 2.355731935983192
fl_caster_l_wheel_joint: 2303.9117993989953
fl_caster_r_wheel_joint: 2468.8539379256895
fl_caster_rotation_joint: -0.7855964009142032
fr_caster_l_wheel_joint: -1962.6303188481893
fr_caster_r_wheel_joint: -1812.2672281283776
fr_caster_rotation_joint: 0.7872200605797226
head_pan_joint: -9.249018477611539e-05
head_tilt_joint: 1.0728538912009142
l_elbow_flex_joint: -1.919922381206603
l_forearm_roll_joint: -0.34919022050429266
l_gripper_joint: 0.08644129011040648
l_gripper_l_finger_joint: 0.5043376890868512
l_gripper_l_finger_tip_joint: 0.5043376890868512
l_gripper_motor_screw_joint: 0.0
l_gripper_motor_slider_joint: 0.0
l_gripper_r_finger_joint: 0.5043376890868512
l_gripper_r_finger_tip_joint: 0.5043376890868512
l_shoulder_lift_joint: 0.8726545105347081
l_shoulder_pan_joint: 1.30900678614617
l_upper_arm_roll_joint: 1.9197462652738873
l_wrist_flex_joint: -0.17464744792839326
l_wrist_roll_joint: -0.17455149038717366
laser_tilt_mount_joint: 0.4299841839399005
r_elbow_flex_joint: -2.0506503335859287
r_forearm_roll_joint: 4.584582902038177
r_gripper_joint: 0.08704873817414047
r_gripper_l_finger_joint: 0.5082783783631448
r_gripper_l_finger_tip_joint: 0.5082783783631448
r_gripper_motor_screw_joint: 0.0
r_gripper_motor_slider_joint: 0.0
r_gripper_r_finger_joint: 0.5082783783631448
r_gripper_r_finger_tip_joint: 0.5082783783631448
r_shoulder_lift_joint: 0.10846794379949935
r_shoulder_pan_joint: -0.6483372056934948
r_upper_arm_roll_joint: -1.1107506377386362
r_wrist_flex_joint: -1.9900264969748427
r_wrist_roll_joint: -3.3873396124245696
torso_lift_joint: 0.29982514252114517
torso_lift_motor_screw_joint: 0.0
```
